{% set version = '1.14.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-proc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pROC_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pROC/pROC_{{ version }}.tar.gz
  sha256: e0f1c17ada95b5d9b4ed4a98bd292e76abf228c57c5f95594071aa58e4be214e

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: microbenchmark, tcltk, MASS, logcondens, doParallel, testthat, vdiffr, ggplot2
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-rcpp >=0.11.1
    - r-ggplot2
    - r-plyr

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp >=0.11.1
    - r-ggplot2
    - r-plyr

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('pROC')"           # [not win]
    - "\"%R%\" -e \"library('pROC')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://expasy.org/tools/pROC/
  license: GPL (>= 3)
  summary: Tools for visualizing, smoothing and comparing receiver operating characteristic (ROC
    curves). (Partial) area under the curve (AUC) can be compared with statistical tests
    based on U-statistics or bootstrap. Confidence intervals can be computed for (p)AUC
    or ROC curves.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: pROC
# Type: Package
# Title: Display and Analyze ROC Curves
# Version: 1.14.0
# Date: 2019-03-12
# Encoding: UTF-8
# Depends: R (>= 2.14)
# Imports: methods, plyr, Rcpp (>= 0.11.1)
# Suggests: microbenchmark, tcltk, MASS, logcondens, doParallel, testthat, vdiffr, ggplot2
# LinkingTo: Rcpp
# Authors@R: c(person("Xavier", "Robin", role = c("cre", "aut"),  email = "pROC-cran@xavier.robin.name", comment = c(ORCID = "0000-0002-6813-3200")), person("Natacha", "Turck", role = "aut"), person("Alexandre", "Hainard", role = "aut"), person("Natalia", "Tiberti", role = "aut"), person("Frederique", "Lisacek", role = "aut"), person("Jean-Charles", "Sanchez", role = "aut"), person("Markus", "Muller", role = "aut"), person("Stefan", "Siegert", role = "ctb",  comment = "Fast DeLong code",  email = "stefan_siegert@gmx.de"), person("Matthias", "Doering", role = "ctb",  comment = "Hand & Till Multiclass"))
# Description: Tools for visualizing, smoothing and comparing receiver operating characteristic (ROC curves). (Partial) area under the curve (AUC) can be compared with statistical tests based on U-statistics or bootstrap. Confidence intervals can be computed for (p)AUC or ROC curves.
# License: GPL (>= 3)
# URL: http://expasy.org/tools/pROC/
# BugReports: https://github.com/xrobin/pROC/issues
# LazyLoad: yes
# NeedsCompilation: yes
# Packaged: 2019-03-12 16:28:21 UTC; xavier
# Author: Xavier Robin [cre, aut] (<https://orcid.org/0000-0002-6813-3200>), Natacha Turck [aut], Alexandre Hainard [aut], Natalia Tiberti [aut], Frederique Lisacek [aut], Jean-Charles Sanchez [aut], Markus Muller [aut], Stefan Siegert [ctb] (Fast DeLong code), Matthias Doering [ctb] (Hand & Till Multiclass)
# Maintainer: Xavier Robin <pROC-cran@xavier.robin.name>
# Repository: CRAN
# Date/Publication: 2019-03-12 18:00:10 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
