travis:
  secure:
    BINSTAR_TOKEN: utFhK6SLCfbx2gVSP+2I1oRJPhujBDWmaEijrLJ1uOV4Edw1v8G5Y+MObTmTXDwEcUuo0zBHk+zgmN20jtpGYJO//GPMIzfyZ1pjGy5+1y7MNzIYM1MskQI3QuJ3nErLSPYDUoWPYdZSq+bMPsL9mPIzJnE7Ocmf6WcPUKM6bCsx3xgnm8IlUmM7/uhKGv1mzfapZUPS0/uUf9dFePEm6mP0my1tSjJ/NjYFyVEdWdrwu2bUOXmkPK/H3eCzRQ6j6G3tm9HmBKgEh0bS0N7yVv0giamE5Jw9kW0+9FsQu0BlKA+VcpzmhOyzzGRTtYIdDk1ogP6rAOyai5n1m4JvUXurnpnr300jBy4JjqLp2powrxRVlSiAAti+qNFosADb31i8pHIEHyO6qeEAxALDtduP/gGBl3pv9j7lVThs3BQ2BirPg3A5Qe/DQVWtIkYfITXWkAsDzyfFQbxh5dd3fYB7K7sNPAJpEW+ufyiPOL8idoWIFAiGY1xc9vo70fzfbkLQ6d9uMqULPknlvckLDZNChkBSQlPGr2rrp76Kn8PRjAiMNDXOBw46VVdV0PEIosqYMcG+tkEoNCYBX+FyM/WV3gZolHEb2Z8SYkfxTBM9VBosKRggCaieHut6/wuTY5aYLS6CJxuiCpcjD3aPVk5xd5bh+lgr7wl+p6PwwL0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
