travis:
  secure:
    BINSTAR_TOKEN: NQfEuXW001IVZFZ8/eIGRgFYpzSU/iY6obVTUZg9eBF2u1Qo4v9qm1CP8XOqtj7SgnjYY1Tnwpfjb5EjmGpEnCdF17GY7/o24AeoUHwcvH4Zt2pjM+uFTIFt1dw5wlR98Q73rRQJOVCBcL1YKIRB0ey8ZlkUICK+VY5VQ3pN2l4ePPnIj3WZy6zjc4Qb3SukWSUaz4kqGMjA4bNJTbExSpj6skO0osDap67k9J+MZvXIYMgwRfpE8EANM0cjcDaOXPtolIU0NJju6ptkIKqb3EoQw0YtEsNx7j0Q6UYLSlESsmqE09fO0nYhlDEY89UF+Xn05bIOhX21O6T3BKLEkmxtHOtJkB815OONjmLNg8q/bTq2rKjH2BYZ4F5qNModUZS6umqmM+dtBMgEFhNU9XGGDKpRpTGB19NwPQvcxjdGzGs+9MHAUl360PewewVpVmB05yPL8JvqpkpjDgFX/NJswm4976VFMjJ/u6DMMSYCafAsX2I13bjbjYdJ/2OWjxms6uYXb7E4npR9zJS5zl7+1DhjVl2AG6qd4MZVfvRCidWT2Ii+cYQNOqFlQOSpi5IXQ7VO3kkKMCo3Dzfi1nyaVK49wgEW7l8Er8AmdWS7OM4QS1FJCPgCiJU6Sd3ELBg3DJCjo6iHvysSuck9P1ZYrCio32K4pirR6qy9dc0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
