travis:
  secure:
    BINSTAR_TOKEN: orsHHkFr09Ls/exwXWN5iryqfrGIQ2Osure4V7ilBNxNy5Lg+CpKXPJGshGjcJ7mnSzXsekw+zI3yY0EhPXhk1Z7bGnb6z6mkpTER+zMbzV5o7xUsgIpvp5bBOZ9+fV9sipAbWpJc1xy48IKFs18o0pVBB28o8ZgxX6zTHrFEa6XF4kG+fP/DulvBPL3CX3SEHQKGtPKDGYRiirq+FOOLMmzQEPUn7Jq/WSAqxEG01WDIn9+2tmdVH9ryvc2qu0LtZIylWsq7mWHeymUyCSXEPwanaiC5Rr0h24LdkpuuPANlTDYbt+noaUJaJZZMhTkqO+8If50Z5YMSLpSqjxsCVAAlq63zSnvveKPRlnSJACQKtEjNtF3xkW6PaRFoK2KLdC1ITBfh8wb05+U5pD5ngajfUIUvT0OQ/yYMVqolfsyKdAbRqJayhIOwt6UJlUTBgT/Zi81DzXvSufuar9xLIgiHCBgV3rJJ9qsH3tGCiZy/NMhRSJxkF3i/Zx5dB9d2dhbIWoL+dLI+Z3uBQpoP3x8NwHm4qNqYTzPQldC0w4Yi9Xp5XS4SkyNE3QbGapLGhySlAkyD+uBKItEK3jXon7RyF2+oM5FL/V4Z1AYqlsFsN4IRRwAQfPwfTl4E+Q70eHr+yd/+eZ4D+ss767aL/WUt58hGMMciKFVwlmxCzs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
